export const adminResources = [
  {
    slug: 'rsvps',
    label: 'Launch RSVPs',
    singularLabel: 'launch RSVP',
    description: 'Review launch responses. RSVPs are created by guests from the public form.',
    allowCreate: false,
    allowDelete: false,
    readOnly: true,
    perPage: 50,
    export: {
      label: 'Download XLS',
      endpoint: '/admin/rsvps/export',
    },
    fields: [
      { name: 'name', type: 'text', label: 'Full name', readonly: true },
      { name: 'email', type: 'email', label: 'Email address', readonly: true },
      { name: 'attending', type: 'checkbox', label: 'Attending', readonly: true },
      { name: 'guests', type: 'number', label: 'Guests', readonly: true },
      { name: 'note', type: 'textarea', label: 'Note', readonly: true },
    ],
  },
  {
    slug: 'articles',
    label: 'Articles',
    singularLabel: 'article',
    description: 'Long-form essays for Research & Ideas.',
    fields: [
      { name: 'category_id', type: 'select', label: 'Category', source: 'categories', optionLabel: 'name', valueType: 'number' },
      { name: 'pillar_id', type: 'select', label: 'Pillar', source: 'pillars', optionLabel: 'title', valueType: 'number' },
      { name: 'slug', type: 'text', label: 'Slug', help: 'Lowercase URL key, for example enterprise-as-stewardship.' },
      { name: 'title', type: 'text', label: 'Title' },
      { name: 'excerpt', type: 'textarea', label: 'Excerpt', rows: 3 },
      { name: 'body', type: 'textarea', label: 'Body', rows: 12 },
      { name: 'published_at', type: 'date', label: 'Published date' },
      { name: 'is_featured', type: 'checkbox', label: 'Feature on homepage' },
    ],
  },
  {
    slug: 'journal-entries',
    label: 'Journal',
    singularLabel: 'journal entry',
    description: 'Shorter reflections and field notes.',
    fields: [
      { name: 'category_id', type: 'select', label: 'Category', source: 'categories', optionLabel: 'name', valueType: 'number' },
      { name: 'slug', type: 'text', label: 'Slug' },
      { name: 'title', type: 'text', label: 'Title' },
      { name: 'excerpt', type: 'textarea', label: 'Excerpt', rows: 3 },
      { name: 'body', type: 'textarea', label: 'Body', rows: 10 },
      { name: 'published_at', type: 'date', label: 'Published date' },
    ],
  },
  {
    slug: 'books',
    label: 'Books',
    singularLabel: 'book',
    description: 'Published, featured, and future authored works.',
    fields: [
      { name: 'slug', type: 'text', label: 'Slug' },
      { name: 'title', type: 'text', label: 'Title' },
      { name: 'subtitle', type: 'text', label: 'Subtitle' },
      { name: 'description', type: 'textarea', label: 'Description', rows: 10 },
      { name: 'cover_image_path', type: 'text', label: 'Cover image path', placeholder: '/images/entrusted-mock.jpg' },
      { name: 'is_featured', type: 'checkbox', label: 'Featured book' },
      { name: 'order', type: 'number', label: 'Display order' },
    ],
  },
  {
    slug: 'pillars',
    label: 'Pillars',
    singularLabel: 'pillar',
    description: 'The six core disciplines that structure the body of work.',
    fields: [
      { name: 'slug', type: 'text', label: 'Slug' },
      { name: 'title', type: 'text', label: 'Title' },
      { name: 'subtitle', type: 'text', label: 'Subtitle' },
      { name: 'description', type: 'textarea', label: 'Description', rows: 5 },
      { name: 'order', type: 'number', label: 'Display order' },
    ],
  },
  {
    slug: 'projects',
    label: 'Projects',
    singularLabel: 'project',
    description: 'CMS-managed project records attached to pillars.',
    fields: [
      { name: 'pillar_id', type: 'select', label: 'Pillar', source: 'pillars', optionLabel: 'title', valueType: 'number' },
      { name: 'slug', type: 'text', label: 'Slug' },
      { name: 'title', type: 'text', label: 'Title' },
      { name: 'summary', type: 'textarea', label: 'Summary', rows: 4 },
      { name: 'content', type: 'textarea', label: 'Content', rows: 10 },
    ],
  },
  {
    slug: 'categories',
    label: 'Categories',
    singularLabel: 'category',
    description: 'Taxonomy for articles and journal entries.',
    fields: [
      { name: 'slug', type: 'text', label: 'Slug' },
      { name: 'name', type: 'text', label: 'Name' },
      { name: 'description', type: 'textarea', label: 'Description', rows: 4 },
    ],
  },
  {
    slug: 'media-items',
    label: 'Media',
    singularLabel: 'media item',
    description: 'Interviews, videos, podcasts, images, and downloadable records.',
    fields: [
      { name: 'pillar_id', type: 'select', label: 'Pillar', source: 'pillars', optionLabel: 'title', valueType: 'number' },
      {
        name: 'type',
        type: 'select',
        label: 'Media type',
        options: [
          { value: 'interview', label: 'Interview' },
          { value: 'tv', label: 'TV' },
          { value: 'podcast', label: 'Podcast' },
          { value: 'video', label: 'Video' },
          { value: 'image', label: 'Image' },
          { value: 'download', label: 'Download' },
        ],
      },
      { name: 'slug', type: 'text', label: 'Slug' },
      { name: 'title', type: 'text', label: 'Title' },
      { name: 'description', type: 'textarea', label: 'Description', rows: 5 },
      { name: 'url', type: 'url', label: 'URL' },
      { name: 'thumbnail_path', type: 'text', label: 'Thumbnail path', placeholder: '/images/example.jpg' },
      { name: 'published_at', type: 'date', label: 'Published date' },
    ],
  },
  {
    slug: 'impact-metrics',
    label: 'Impact Metrics',
    singularLabel: 'impact metric',
    description: 'Public-facing numerical highlights.',
    fields: [
      { name: 'slug', type: 'text', label: 'Slug' },
      { name: 'label', type: 'text', label: 'Label' },
      { name: 'value', type: 'text', label: 'Value' },
      { name: 'description', type: 'textarea', label: 'Description', rows: 4 },
      { name: 'order', type: 'number', label: 'Display order' },
    ],
  },
  {
    slug: 'quotes',
    label: 'Quotes',
    singularLabel: 'quote',
    description: 'Featured statements used across the site.',
    fields: [
      { name: 'text', type: 'textarea', label: 'Quote text', rows: 5 },
      { name: 'source', type: 'text', label: 'Source' },
      { name: 'is_active', type: 'checkbox', label: 'Active' },
    ],
  },
  {
    slug: 'convictions',
    label: 'Convictions',
    singularLabel: 'conviction',
    description: 'Guiding convictions shown on the About page.',
    fields: [
      { name: 'title', type: 'text', label: 'Title' },
      { name: 'description', type: 'textarea', label: 'Description', rows: 5 },
      { name: 'order', type: 'number', label: 'Display order' },
    ],
  },
  {
    slug: 'content-blocks',
    label: 'Content Blocks',
    singularLabel: 'content block',
    description: 'Page-level copy blocks, launch details, and structured metadata.',
    fields: [
      { name: 'context', type: 'select', label: 'Context', options: ['home', 'about', 'build_tomorrow', 'speaking', 'mentorship', 'impact'] },
      { name: 'slug', type: 'text', label: 'Slug', help: 'Keep existing slugs stable because pages read them directly.' },
      { name: 'title', type: 'text', label: 'Title' },
      { name: 'body', type: 'textarea', label: 'Body', rows: 10 },
      { name: 'meta', type: 'json', label: 'Metadata JSON', rows: 12, help: 'Use valid JSON for images, dates, venue details, and other structured fields.' },
      { name: 'order', type: 'number', label: 'Display order' },
    ],
  },
  {
    slug: 'contact-messages',
    label: 'Contact Messages',
    singularLabel: 'contact message',
    description: 'Review enquiries submitted from the public contact and enquiry forms.',
    allowCreate: false,
    allowDelete: false,
    readOnly: true,
    perPage: 50,
    fields: [
      { name: 'name', type: 'text', label: 'Name', readonly: true },
      { name: 'email', type: 'email', label: 'Email address', readonly: true },
      { name: 'subject', type: 'text', label: 'Subject', readonly: true },
      { name: 'type', type: 'text', label: 'Type', readonly: true },
      { name: 'message', type: 'textarea', label: 'Message', rows: 8, readonly: true },
      { name: 'created_at', type: 'text', label: 'Received at', readonly: true },
    ],
  },
  {
    slug: 'newsletter-subscribers',
    label: 'Newsletter Subscribers',
    singularLabel: 'newsletter subscriber',
    description: 'Review people who have subscribed through the public newsletter form.',
    allowCreate: false,
    allowDelete: false,
    readOnly: true,
    perPage: 50,
    fields: [
      { name: 'email', type: 'email', label: 'Email address', readonly: true },
      { name: 'name', type: 'text', label: 'Name', readonly: true },
      { name: 'source', type: 'text', label: 'Source', readonly: true },
      { name: 'created_at', type: 'text', label: 'Subscribed at', readonly: true },
    ],
  },
  {
    slug: 'galleries',
    label: 'Galleries',
    singularLabel: 'gallery',
    description: 'Group media items into curated image and media collections.',
    fields: [
      { name: 'title', type: 'text', label: 'Title' },
      { name: 'description', type: 'textarea', label: 'Description', rows: 4 },
    ],
  },
  {
    slug: 'gallery-items',
    label: 'Gallery Items',
    singularLabel: 'gallery item',
    description: 'Attach media records to galleries and control their display order.',
    fields: [
      { name: 'gallery_id', type: 'select', label: 'Gallery', source: 'galleries', optionLabel: 'title', valueType: 'number' },
      { name: 'media_item_id', type: 'select', label: 'Media item', source: 'media-items', optionLabel: 'title', valueType: 'number' },
      { name: 'order', type: 'number', label: 'Display order' },
    ],
  },
];

export function resourceFor(slug) {
  return adminResources.find((resource) => resource.slug === slug) || adminResources[0];
}
